theme: jekyll-theme-minimal
title: "Eion Mulrenin"
description: <a href=mailto:"eion.mulrenin@emory.edu">eion.mulrenin@emory.edu</a>
logo: https://raw.githubuser.content.com/emulrenin/emulrenin.github.io/main/EM.jpeg
